### ISSUE TITLE
Nudge Suggestion

### ISSUE THREAD

**Issue by dtw2000** [reini1305/alarmsplusplus#11]
It'd be cool to be able to set a nudge alarm.  Something that would basically go off for a quick pulse and wouldn't require a dismissal.  It would auto dismiss.

**Comment by reini1305** [comment]
You can already do that. In the advanced options set the vibration duration as low as 2 seconds and deactivate "snooze after vibration".

**Comment by dtw2000** [comment]
Hmm.  I see what your saying.  I think you still have to acknowledge the alarm to dismiss it and make the screen/animation go away.  If you were to add the extra functionality, you could add a 'None' option along with the 'Easy, Medium, Hard' options in the list of "Dismiss Alarm" choices.  "None" would automatically dismiss and close the screen after the vibration duration or not show a screen at all.  Really this would have to be an alarm setting rather than a global setting for all alarms for it to be useful.  Actually several of your global "Advanced settings" could be useful as individual alarm settings; however, I realize this may be out of the scope of what you really want to consider.  Kudos by the way.

**Comment by reini1305** [comment]
If you set it like I suggested, you don't have to dismiss it. After "vibration duration" the app will quit itself and prepare for the next alarm, so there is no need for a "None" setting. Someone asked me if I could implement a very short vibration time, so I implemented it. Personally, I find it quite useless (it wouldn't wake me up).

You are right that I don't want to implement it as a per-alarm setting, the wakeup code is already quite complicated :)

**Comment by andyb9** [comment]
@reini1305

setting up as you suggested does not dismiss the alarm, the animation still stays on my "Pebble Time Steel" with both the snooze and dismiss buttons showing.

**Comment by andyb9** [comment]
@reini1305

setting up as you suggested does not dismiss the alarm, the animation still stays on my "Pebble Steel Time" with both the snooze and dismiss buttons showing.

**Comment by reini1305** [comment]
Cannot reroduce. Are you sure youre not using the system app?

**Comment by andyb9** [comment]
what do you mean by the system app?

if you mean the system alarm app then no.

Alarm ++ also looks completely different from the system alarm app and has a blue scroll bar and the system alarm app has a green scroll bar.

Also i am using Alarm ++ v7.4 on a Pebble Time Steel (firmware v4.13).

**Comment by dtw2000** [comment]
I'm on a pebble time.  I had the same results as @andyb9 when setting up the alarm per @reini1305 suggestion.

**Comment by andyb9** [comment]
@reini1305 

if you cant reproduce no worries, very nice and useful app and we thank you for creating it as there was and still nothing else like it :-)

**Comment by reini1305** [comment]
Which Versionof the app are you using. It should be functioning the same on all devices.

**Comment by dtw2000** [comment]
I'm not sure which version I was on previously.  I did a fresh install and re-tested this on v7.5.  I get the same results.  The animation plays indefinitely until dismissed.  I didn't press the issue previously since this should be a per alarm setting rather than a global alarm setting, and I understand you don't really want to complicate it further.  I looked at the source code back then and decided the same thing.

**Comment by reini1305** [comment]
When I set the vibration duration to two seconds, the app closes after 2 seconds as intended. On a Pebble 2 with 4.2

**Comment by dtw2000** [comment]
For clarification:

Pebble: Pebble Time
Pebble Version: 4.2
Alarm++ Version: 7.5

Vibration stops after 2 seconds, but the dancing clock continues until you press dismiss.

Strange.

**Comment by reini1305** [comment]
Did you enable snooze after vibration end?

**Comment by reini1305** [comment]
I guess we found an edge case. I just have to close the app when the user decides to disable snooze.

**Comment by dtw2000** [comment]
Did you **enable** snooze after vibration end?  Enabling it seems to make it work as I would expect it to.   You have to set the snooze delay to 0 as well or get indefinite recurring alerts.  I though I tried it both ways previously, but to be fair your instructions were to **deactivate** "snooze after vibration".  

Maybe we did find an edge case.

**Comment by reini1305** [comment]
OK, it was a bug after all. I fixed it in version 7.6 to be distributed soon!
