### ISSUE TITLE
Pins don't show

### ISSUE THREAD

**Issue by tfenster** [reini1305/alarmsplusplus#14]
Almost daily the pin for the next day on my recurring alarms doesn't show up. I have to open the app, go to the alarm and go back out. After approx 30 seconds the pin appears most of the time. Anything I can do about that?

**Comment by reini1305** [comment]
Hi!

 

I know this behaviour and there is not much I can do against it. I push a new pin when the app starts, so I can maximize the timeout (servers are pretty slow). If your watch has a bad connection to the phone or the phone a bad connection to the internet, the pin might get lost in transition. This is especially true if you kill the alarm quickly. Then there is not much time to send a pin.

 

Gesendet: Mittwoch, 09. August 2017 um 17:29 Uhr
Von: tfenster <notifications@github.com>
An: reini1305/alarmsplusplus <alarmsplusplus@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [reini1305/alarmsplusplus] Pins don't show (#14)


Almost daily the pin for the next day on my recurring alarms doesn't show up. I have to open the app, go to the alarm and go back out. After approx 30 seconds the pin appears most of the time. Anything I can do about that?

**Comment by tfenster** [comment]
Ok, makes a lot of sense because usually I turn the alarm off while in bed and without a connection to my phone. What is the easiest / quickest way to reset the pin?
