### ISSUE TITLE
After adding or removing description, alarm is not highlighted properly when you finished editing

### ISSUE THREAD

**Issue by contre** [reini1305/alarmsplusplus#2]
I tried to fix this myself as an exercise in learning pebble programming but was unable to do so.

I found that when you return to the main window after either adding or removing a description, the black background for the selected item is not the right size. It is in fact the size for the previous state of the menu item (small if adding, large if removing).

I am not yet familiar enough with pebble dev to point the finger at where the issue is occurring but I thought I'd report it as I've hit a wall in determining the cause.
![alamrs error](https://cloud.githubusercontent.com/assets/427388/6102372/3062344a-afea-11e4-8efe-04e537246a70.png)

I am beginning to wonder if the fault lies in the pebble menuLayer API.

**Comment by reini1305** [comment]
Thank you for submitting this. I know how to fix it and will upload a new version on Monday when I have access to my development laptop.

**Comment by reini1305** [comment]
fixed in v2.20
