### ISSUE TITLE
Pebble Time: alarms coming late / not at all

### ISSUE THREAD

**Issue by jsquyres** [reini1305/alarmsplusplus#4]
I just received my Pebble Time (yay!) and am using Alarms++.

I've noticed that my daily "wake up!" alarm is coming in a minute or two late.  I don't have hard data on this, though (because I'm usually kinda groggy/just waking up).

With some experimentation right now, however, I notice that setting alarms for <=10 minutes from now do not seem to activate.  For example:
1. Go to the 3rd alarm on my watch (currently unused/off).
2. Middle button, set it to ~3 minutes from now.
3. Get back to the main alarm listing screen, verify that the time is set correctly for ~3 minutes from now and it is "ON"
4. ~4-5 minutes later, realize that the alarm hasn't gone off.
5. Repeat the procedure and set an alarm ~11 minutes from now.
6. ~13-14 minutes later, realize that the alarm hasn't gone off.

Did the basalt/Pebble Time OS update cause something odd to happen with how alarms are scheduled?

**Comment by reini1305** [comment]
Hi! 

It seems that there are some issues regarding wakeup API on Basalt. I'm in contact with pebble and other developers with the same problems. I have no PT and on the emulator everything is fine. I'm hoping for an issue in the OS and a quick fix from Pebble. I will keep you posted.

BTW, thanks for your donation!

**Comment by jsquyres** [comment]
Sweet - glad to hear that this is not specific to alarmsplus!

**Comment by reini1305** [comment]
@jsquyres update: at least Pebble acknowledged the error in: http://developer.getpebble.com/sdk/migration-guide/ if you scroll down to "Known Bugs"

**Comment by jsquyres** [comment]
Coolio.  Hopefully they'll fix it soon.

On Thu, Jun 11, 2015 at 1:27 PM, Christian Reinbacher <
notifications@github.com> wrote:

> @jsquyres https://github.com/jsquyres update: at least Pebble
> acknowledged the error in:
> http://developer.getpebble.com/sdk/migration-guide/ if you scroll down to
> "Known Bugs"
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/reini1305/alarmsplusplus/issues/4#issuecomment-111213730
> .

## 

{+} Jeff Squyres

**Comment by jsquyres** [comment]
Just curious -- is this fixed in the 3.1 firmware update?

**Comment by reini1305** [comment]
@jsquyres there is nothing in the changelog. I fear not :(

**Comment by jsquyres** [comment]
Bummer.

**Comment by reini1305** [comment]
Is this still an issue? I haven't seen it on my Pebble Time in a while...

**Comment by jsquyres** [comment]
I confess I have not checked in a while, sorry! :-(

**Comment by andyb9** [comment]
> Is this still an issue? I haven't seen it on my Pebble Time in a while...

i can definitely say it is still an issue - it happens occasionally on my **Pebble Time Steel** (on lastest **firmware v4.2**), ie alarms dont go off at all and will start going off on the next alarm, and only if i go into the app and then exit it.

it's hard to replicate - 

but i have proven it to myself more than once - _for example_ 
- was expecting a wakeup alarm to go off at 07:15 and it didnt even though set to go off on that day etc etc and the same again on the same day but on 08:45, so decided to go into the app to check if it was indeed set for that particular day & time and it was, however once going into the app, then all alarms after that for that day will go off as expected.

**Comment by reini1305** [comment]
This will be very hard to replicate/fix... My guess is, that the app crashes upon exit, thus it is not able to set the new alarm. You won't get any feedback, because the OS simply closes the app. I saw this happening once to me, where I opened it, and then closed it immediately. It took longer than normal, and the AppGlance has not been set.

I can't do much here because this crash happened after the main loop of my app, so I have to leave this issue closed until we can find a way to replicate it.

**Comment by stuckj** [comment]
I see this same problem as well. It was happening intermittently, but now my alarms almost never work. It's pretty much become unreliable to use. :-( Today, I explicitly opened the app 5 minutes before an alarm was set to go off and just left the app open. It didn't even go off in that case. :-P

**Comment by reini1305** [comment]
> Today, I explicitly opened the app 5 minutes before an alarm was set to go off and just left the app open. It didn't even go off in that case

@stuckj  This is expected behavior. The alarm won't go off when the app is open, this is why it automatically closes itself after 10 minutes of inactivity.

Since neither my code changed in the last time, nor the OS of Pebble, I can only give you two advices:

- perform a factory reset of the watch just to make sure.
- look at the launcher. If the app glance has been set (next alarm in xxh yym), the chances are high that it will ring

**Comment by reini1305** [comment]
Also, make sure that "Standby Mode" in the "System" settings is off. If on (and active), apps are not allowed to vibrate...
