### ISSUE TITLE
Alarms overlapping on days

### ISSUE THREAD

**Issue by kongd** [reini1305/alarmsplusplus#6]
I have the strangest bug still - I have 3 alarms, a Mon/Wed, Tues/Thurs, and Friday alarm, all at different times. Sometimes on a Monday, I'll get both my Mon/Wed and Tues/Thurs alarm, and I sometimes on the weekend, I'll get my weekday alarms.

I've only been able to replicate this bug on Pebble Time.

**Comment by reini1305** [comment]
Can you give me the exact times of the alarms, so that I can try to replicate this bug?

**Comment by kongd** [comment]
Yup!
9:15 AM Mon/Wed
9:35 AM Tues/Thurs
8:15 AM Fri
